### ISSUE TITLE
Créer le design de la vue character

### ISSUE THREAD

**Issue by bmagic** [warcraftlfg/warcraft-lfg#10]
Créer un design de la vue character 

Information à afficher par character : 
- Faction 
- Description (Texte libre de l'user) (can be empty)
- Name 
- Realm 
- Region 
- Guild (can be empty)
- Level 
- ilvl 
- Role (can be empty)
- Ring (can be empty) 
- Languages (can be empty) 
- Raids per week  
- Raids days avec horaires (can be empty)
- Progress (version complète) (can be empty)
- Warcraftlogs (version complète) (can be empty)
- Update Date
- Link vers armory 
- Link vers warcraftlog

**Comment by Zzbrah** [comment]
Fait.
