### ISSUE TITLE
More filters and sorting option

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#120]
As an user, I want to be able to filter and sort my search with more criterias:
- ilvl (e.g: sort people by ilvl , or only show me people with ilvl > Y)
- progress (e.g: only show me guild/character with X/13 Mythic)

**Comment by Raylehnhoff** [comment]
Suggestion for more filters:

Transfer: Server
Transfer: Faction

instead of "Transfer: Allow"

There are a lot of people that are willing to jump servers, but not faction, which is an important distinction.
