### ISSUE TITLE
Add limitation to who can edit a guild ad

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#122]
As a guild master/officer, I want to be able to control who can edit my guild ad.

**Comment by Raylehnhoff** [comment]
As an FYI, the Battle.NET API call `/WOW/GUILD/:REALM/:GUILDNAME?fields=MEMBERS` will return the member list of a guild with a `rank` property on each member.

Guild ranks are ordered in ascending order of position:

| Rank | Typical Position |
| --- | --- |
| 0 | GM |
| 1 | CO-GM |
| 2 | Officer |

all the way to 10, which is typically a "recruit" rank.

If you wanted to provide for this, you would need to allow the administrator of a guild page to define which "rank" integers correspond to their guild's officers.

There is no rank name API call, unfortunately, so the page that would allow this would need the explanation of how ranks map to the in-game guild system.

**Comment by SuperNerdEric** [comment]
In my opinion the default should be rank 0 and 1, but be editable by the person with rank 0. My guild uses 0 for GM, 1 for officer and 2 for raider.
