### ISSUE TITLE
Attempt to Resolve Region Automatically via IP

### ISSUE THREAD

**Issue by Raylehnhoff** [warcraftlfg/warcraft-lfg#127]
APIs exist that will do this with a blank GET request:

http://freegeoip.net/xml/

http://freegeoip.net/json/

I'm not sure how this would work out for Eurozone countries, but it'd be a nice touch for automatic US region resolution.

**Comment by cdrandin** [comment]
@Raylehnhoff Using a VPN testing for Euro countries shows the service to be working properly. Neat site for sure.

**Comment by bmagic** [comment]
EU region is hardcoded on homepage. I had it on backlog list, I will use navigator language for this, I think is better than GeoIp.
Thx for your report

**Comment by Raylehnhoff** [comment]
@bmagic I'd caution against `navigator.language` based on my experiences with it. For example, German users will have the culture string `de` or `de-DE`, which wouldn't help you resolve them to Europe without using another lookup. Geolocating is more reliable for figuring out what region someone is in than their language settings, but obviously at the end of the day it's your call :)
