### ISSUE TITLE
Add a markdown processor for richtext formatting

### ISSUE THREAD

**Issue by Raylehnhoff** [warcraftlfg/warcraft-lfg#129]
The reddit thread highlighted some desire for rich text formatting for users. Markdown being the format used by Reddit is simple to implement, and has robust javascript libraries for it to integrate into this project.

There's a lot of options out there, but [SimpleMDE](http://nextstepwebs.github.io/simplemde-markdown-editor/) is pretty nice.

**Comment by bmagic** [comment]
Yes it's a good idea !!! Go to backlog list

**Comment by yz0** [comment]
Done by #186 ! :)

**Comment by Raylehnhoff** [comment]
Nice work!
