### ISSUE TITLE
[Documentation/Suggestion] Provide better instructions for getting the site running

### ISSUE THREAD

**Issue by Raylehnhoff** [warcraftlfg/warcraft-lfg#132]
You're missing a step between `Grunt Configuration` and `Launch` wherein the webserver needs to be told to start via something like

`sudo node server -ws start webserver` 

I'm not a node/angular developer by trade, so for whatever reason this was totally lost on me.

It would also be VERY helpful to document the parameters and what exactly they'll be doing.

**Comment by bmagic** [comment]
Wiki is up to date
