### ISSUE TITLE
[Suggestion] Add better page titles

### ISSUE THREAD

**Issue by Raylehnhoff** [warcraftlfg/warcraft-lfg#133]
A huge gripe that I have with WarcraftLogs (and others), is that they don't dynamically set page titles, which makes it impossible for me to type the name of my guild in the URL bar and get a "smart recommendation" for our page.

It looks like this could be done in the `guild.js` file. The code would be something like:

`document.title = guild.name + " - " + guild.realm + " - " + guild.region + " - WarcraftLFG";`, though you may want to create some plumbing to dynamically set the strings.

Just a thought :)

**Comment by yz0** [comment]
Should be good with #193
