### ISSUE TITLE
Guild Showing Wrong Progress

### ISSUE THREAD

**Issue by SuperNerdEric** [warcraftlfg/warcraft-lfg#135]
My guild https://www.warcraftlfg.com/#/guild/us/Korgath/Re%20Lapse/ is showing as 11/13M but we are 12/13M. It shows we have only killed Iron Reaver on Heroic.

If you look at http://www.wowprogress.com/guild/us/korgath/Re+Lapse you can see we have killed Iron Reaver on Mythic 12 times. 

Here's someone on Reddit with the same problem https://www.reddit.com/r/wow/comments/3vszzx/introducing_warcraftlfg/cxqruy9

**Comment by bmagic** [comment]
We have not realy a solution for this ... If you look the armory Api of blizzard they just give us the last kill for each boss... So we start progress one week ago and we have only the kill where 8 (Heroic or Normal) and 16 players (Mythic) share the same timestamp kill.

I will add some improvement (use Mythic achievement etc) but for the progress if you don't parse characters each weeks you can't have all kills. 

It will be fine for Legion.

See -> https://github.com/warcraftlfg/warcraft-lfg/issues/136
