### ISSUE TITLE
Timezone changes

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#147]
- Remove all current used timezone
- add official server timezone instead as per Blizzard API
- allow filter on Servers timezone

Currently, too many timezone means it's very easy to filter out relevant guild. By limiting timezones to the server timezone, we remove this issue. This will allow us to filter and sort easily things like OCE people, East Coast vs West Coast US etc

**Comment by bmagic** [comment]
I like this !!!

**Comment by bmagic** [comment]
:+1:

**Comment by bmagic** [comment]
I will create zone like this : 
us-en_US-America/Chicago
us-en_US-America/Los_Angeles
us-en_US-America/New_York
us-en_US-America/Denver
us-en_US-Australia/Melbourne
us-es_MX-America/Chicago
us-pt_BR-America/Sao_Paulo
eu-en_GB-Europe/Paris
eu-pt_BR-Europe/Paris
eu-de_DE-Europe/Paris
eu-fr_FR-Europe/Paris
eu-ru_RU-Europe/Paris
eu-es_ES-Europe/Paris
tw-zh_TW-Asia/Taipei
kr-ko_KR-Asia/Seoul
