### ISSUE TITLE
[Dev] Authenticating Localhost?

### ISSUE THREAD

**Issue by Raylehnhoff** [warcraftlfg/warcraft-lfg#152]
I have a bnet API key, but I'm not really clear on how to authenticate locally. Can you provide some documentation about this?

**Comment by bmagic** [comment]
I do it now !!!

**Comment by Raylehnhoff** [comment]
My fault. I didn't have the callback registered properly on dev.battle.net.

**Comment by Raylehnhoff** [comment]
I'm going to write a markdown file that documents this step for people.

**Comment by bmagic** [comment]
Merged !! Thx
