### ISSUE TITLE
Bug: No class icon / No style added to a recently updated character

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#18]
Bug fix tout seul après un refresh de la page.

![capture](https://cloud.githubusercontent.com/assets/7361756/11424758/b5dea300-9447-11e5-8458-6581794f13cc.PNG)

**Comment by bmagic** [comment]
Cela s'explique tout simplement quand je rajoute une annonce de personnage je balance un événement à tous les gens connecté pour leur dire qu'il y a une nouvelle anonce  et update la page d'accueil dynamiquement. Cependant à ce moment précis j'ai pas encore récupérer la fiche de personnage et du coup je ne connais pas la classe etc etc.
Ca arrive en général pas bien longtemps apres, mais je ne peux pas balancer à chaque fois que je recois un personnage l'information à tout le monde car cela serait bandepassanteophage (je parse 10 persos par seconde).

Bref ce n'est pas simple sauf si je vire l'update automatique sur la page d'accueil

**Comment by bmagic** [comment]
It's fixed since refactoring of January.
