### ISSUE TITLE
Production node version is unspecified.

### ISSUE THREAD

**Issue by vikeen** [warcraftlfg/warcraft-lfg#180]
- package.json should be clear about the node engine version
- travis.yml should run in this version plus any backwards compatibable version

Optionally it would be nice to have a .nvmrc with the latest supported version as well.

**Comment by bmagic** [comment]
Yes you are right ... 
I focus on creating priority funtionalities (Sort / improved progress & filters) and after I make a big refactoring session on all my code (Unit Test + Rewrite)

**Comment by vikeen** [comment]
Understood. I was just creating a ticket for future visibility.

**Comment by bmagic** [comment]
Corrected in v2 branch
