### ISSUE TITLE
Documentation Update - config.dev.json 

### ISSUE THREAD

**Issue by vikeen** [warcraftlfg/warcraft-lfg#182]
There doesn't seem to be any documentation on setting up the config.dev.json for local development. It is also misleading to have a default.json when nothing is actually in there is actually be used as a default. Atleast that is the way I read this type of architecture. Maybe default is meant to be a default environment  entirely and not a default key-value store for keys that aren't found in other environment configs?

In either case it is difficult to get started locally. The API guides for battle.net and warcraftlogs are a great addition, but a bit more is needed for local system configuration.

**Comment by vikeen** [comment]
Another example:

The README.md documenation says to use `grunt` to boot the local server. This default command is only configured to run clean and watch commands.

``` js
module.exports = function(grunt) {
    grunt.registerTask('default', ['clean','watch']);
    //TODO Add File inside index.html
};
```

Instead I found myself running

``` shell
NODE_ENV=dev node server/server.js -ws
```

Which then gives an error about a log directory missing.

``` shell
debug: Redis connected
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'logs/all.log'
    at Error (native)
```

A quick `mkdir logs` and things boot up as I would expect

``` shell
╭─johnrake@c2fos-MBP-5  ~/dev/personal/warcraft-lfg ‹v5.0.0› ‹master*› 
╰─$ NODE_ENV=dev node server/server.js -ws
debug: Redis connected
debug: Mongodb connected
info: Server HTTP listening on port 3000
info: Anonymous user connected
```

Edit: I now see that -ws is proably not what I want. Any ideas here? Running without parameters chugs away with a bunch of stuff until it croaks on some malformed json.

**Comment by vikeen** [comment]
I forgot to mention, but I assume a node version of 5.0.0 since it's the fairly recent and nothing specified a version quirement that I could find.

**Comment by Raylehnhoff** [comment]
You make a copy of the .default.json with .dev.json with your API keys filled in

After that, grunt the directory which will setup a file watcher to copy future saved files

After that run:

`sudo node server/server` (assuming project root) which will spin up the service.

The documentation needs a lot of improvements.

**Comment by Raylehnhoff** [comment]
To be clear, this is the file you make a copy of and setup:

https://github.com/warcraftlfg/warcraft-lfg/blob/master/server/app/config/config.default.json

The copy should be in the same config directory.

**Comment by vikeen** [comment]
Ok. Ya, that is the basics of what I was gathering I just missed the grunt interaction and how to actually start the server.

Thanks.

**Comment by bmagic** [comment]
If you run gunt without param it will watch on folder client and copy files into www , create css & jshint.
see grunt/config/watch.js

If you run node server/server.js without params you will have all process runing. 
I create args (-ws -cu ...) because I want to run 10 or more Character Update process (node server/server.js -cu).

The doc is not really accurate now ... I expect starting create a real doc (with readthedoc) for the new year.

**Comment by Raylehnhoff** [comment]
@vikeen if you wanted to write up your experiences and commit it to the documentation, it'd be really helpful. I'd be happy to assist you in getting it written up if you wanted. I had to fumble through setting up a virtualbox VM just to run this app, so I feel your pain acutely.

**Comment by vikeen** [comment]
@bmagic thanks for the clarification. I do realize this is still in beta and was only recently made public knowledge. Thanks for your efforts here. I believe this has the potential to be an amazing addition the WoW ecosystem.

**Comment by vikeen** [comment]
@Raylehnhoff other than the the clarification or how to utilize `server/server.js` and the config setup I didn't have any major issues. The updated doc section on API keys saved a ton of time.

**Comment by bmagic** [comment]
Yes we release public 4 days ago. We want user feedbacks to be ready for Legion and to know if this project make sense.
We have a lot of good feedback and functionalities.
So first step is implement "MUST HAVE" functionalities and after I refactoring and make documentation.

**Comment by Raylehnhoff** [comment]
Thanks @vikeen, I wrote that document. 

@bmagic I don't think anyone is upset with the projects rapid development. You guys are doing great, I just think people are eager to help. I've thought about a system like this for a long time myself, which probably explains my involvement here - I have a very high interest in helping this along in any way that I can.

**Comment by dmartin-gh** [comment]
I too just got up and running. I'm using a Parallels VM with CentOS 7 and the following package versions:

```
Node.js == 5.2.0
Redis == 2.8.19
MongoDB == 2.6.11
```

The site seems to be functioning correctly. If those are not the versions you're targeting please let me know.

I gave the VM a 400GB drive. What kinds of data volumes are you seeing in a development environment? Is that overkill or not enough?

As far as the ease of the setup, it went pretty smoothly (assuming you already have experience with Node.js environments and the package manager on your OS). Additional documentation is alway nice but I agree with @bmagic; right now is feature-crunch time.

**Comment by bmagic** [comment]
I'm starting a draft  on wiki page with the release of V2 branch in the next days. 
https://github.com/warcraftlfg/warcraft-lfg/wiki
