### ISSUE TITLE
Filters : Hours

### ISSUE THREAD

**Issue by yz0** [warcraftlfg/warcraft-lfg#234]
Add a filter to search by hours.

**Comment by bmagic** [comment]
I'm on it tonight :) 
1. Change the time select format start & end become integer (Back & front) 
   start 21h15 = 21x100+15 =2115 and end 04h30 = (4+30)x100+15= 3415
2.  Add playtime.timezone (integer) object 
   3 . Add filter on guild List (Start End)
3. Create UpdateScript to convert old time to new time.

**Comment by bmagic** [comment]
OK I'have finished some parts  (2e6bd2e63dd6dcf27c3770e519d62277fc19f6c1)
1. Reset API for guild 
2. Update interface 

I need to do 
1. Add filter on guild List 
2. Create an update script to convert old time format to new time

Finally I don't use x100 format hour. I use a timestamp an add 1 day for the end date. :+1: for moment.js
