### ISSUE TITLE
Create Mail message for expire ad

### ISSUE THREAD

**Issue by bmagic** [warcraftlfg/warcraft-lfg#298]
We need a message in English & French for Expire Ad.

**Comment by bmagic** [comment]
In french something like, maybe to improve !!! 

Bonjour [Btag], 

ton annonce de recherche de personnage [Name]@[Serveur]([REGION]) va expirer dans [N] jours. 
Afin que ton annonce soit toujours visible il suffit de se connecter dans l'interface et de la mettre à jour. 

-- The warcraftlfg Team

**Comment by bmagic** [comment]
En y réfléchissant bien ce serait plus un truc comme ça : 

Bonjour [Btag],

Nous t'envoyons ce message afin de te prévenir qu'au moins une de tes annonces va bientôt expirer.
Afin que tes annonces soit toujours visibles il suffit de se connecter dans l'interface et de les mettre à jour.

Les annonces qui vont bientôt expirer : 
- [NAME]@[REALM]([REGION]) expire dans [N] jours.
- ...

Pour rappel une annonce de personnage à une durée maximale de 30J et une annonce de guilde un durée maximale de 4 mois. 

Merci encore de ta confiance.

-- The warcraftlfg Team

**Comment by daleadae** [comment]
Done 

https://warcraftlfg.slack.com/files/tyrus/F18V7LQ10/Expire_ads
