### ISSUE TITLE
Translate / Improve FAQ text

### ISSUE THREAD

**Issue by bmagic** [warcraftlfg/warcraft-lfg#302]
Can you Improve & translate the new FAQ ? 

> - Qu'est-ce que c'est WarcraftLFG ?
>   WarcraftLFG a été créé à partir d'un constat : il n'existe actuellement aucun moyen simple et complet pour rechercher une guilde ou un joueur.
>   Avec WarcraftLFG vous pouvez effectuer une recherche sur une guilde avec de nombreux critères comme sa progression issue de wowprogress, ou vous pouvez effectuer une recherche sur un personnage en ayant rapidement un retour de ses performances avec ses logs warcraftlogs.
> - D'où viennent les données ? 
>   Nous ne voulons pas réinventer la roue, nous utilisons les données sur les sites là où elles existent. 
>   Wowprogress propose aux joueurs et aux guildes de se mettre en recherche de guilde -->nous importons ces données en temps réel.
>   Wowprogress propose un classement des guildes --> nous l'utilisons 
>   Warcraftlogs propose un aperçu des performances utilisateurs --> nous l'utilisons  
>   [Insérer l'image de la page d'accueil ici @Zzbrah]
> - Wowprogress propose déjà un système de recherche non ?
>   Wowprogress propose un système de recherche, mais malheureusement ce site n'est pas dédié à la recherche et ne permet pas de trouver facilement une guilde ou un joueur. Il y a malheureusement que très peu de critères permettant de cibler une recherche.
> - Si je m'inscrit vous allez voler mon compte wow ? 
>   Il n'y a aucun risque la dessus, nous utilisons l'authentification OAuth. OAuth permet aux utilisateurs de donner, au site ou logiciel « consommateur », l'accès à des informations personnelles provenant du site « fournisseur » de service ou de données, ceci tout en protégeant le pseudonyme et le mot de passe des utilisateurs. (Source : https://fr.wikipedia.org/wiki/OAuth). Blizzard permet uniquement de récupérer des informations sur la liste des personnages nous ne voulons et nous ne pourrons modifier aucune de vos données.
>   De plus l'ensemble du code est totalement opensource (Licence AGPL3) et disponible sur github : https://github.com/warcraftlfg/warcraft-lfg 
> - Qui sommes nous ? 
>   Joueurs de wow depuis plus de 11 ans, nous sommes une équipe de passionnés qui ont eu des soucis de recrutement dans nos guildes respectives. Nous essayons avec warcraftLFG de proposer le système qui aidera le mieux les joueurs et les guildes dans leur recherche de guilde.

**Comment by daleadae** [comment]
> - What is WarcraftLFG ?
>   WarcraftLFG comes from the realizing that guild recruitment lacks a proper, simple and complete tool. 
>   WarcraftLFG will allow you to search for a guild based on many criteria, such as its progress. It will also allow you to find a character to recruit, based on its performance.
> - Where are your data coming from ? 
>   From popular and well known community websites:
>   Wowprogress provides us with players and guilds who started to look for guilds/members. As such we import this data in real time. 
>   Wowprogress also provides us with guild ranks. 
>   Warcraftlogs offers a great overview of a player's performance.

[Insérer l'image de la page d'accueil ici @Zzbrah]

> - Why not use Wowprogress search feature ?
>   Wowprogress was not designed with the intent of guild recruitment and such lacks proper features. We offer a larger range of criteria to help you find the perfect guild/players. 
> - Why do I need to log in using my Battle.net account? 
>   Using  OAuth, a system providing by Blizzard itself, is the most secure and efficient way to gather your character information (names & realms) while keeping any sensitive information to your account (password, email etc) perfectly secure. (Source : https://www.wikipedia.org/wiki/OAuth).
>   Our code is open source and visible to all (AGPL3 Licensed) through Github: https://github.com/warcraftlfg/warcraft-lfg 
> - Who are we?  
>   Like you, players of World of Warcraft since closed beta back in 2004. We are passionate raiders who had their share of issues recruiting compatible members through the years. Our goal with WarcraftLFG is to help players and guilds finding each other quickly and efficiently.

**Comment by dmartin-gh** [comment]
> the realizing that
> the realization that
> 
> on its performance
> on their performance
> 
> Where are your data coming from ?
> Where is your data coming from?
> 
> Wowprogress provides us with players and guilds who started to look for guilds/members. As such we import this data in real time.
> Wowprogress provides us with a starting set of players and guilds; we import this data in real time.
> 
> Why not use Wowprogress search feature ?
> Why not use the Wowprogress search feature?
> 
> and such lacks proper
> and therefore lacks appropriate
> 
> a system providing by
> a system provided by
> 
> who had their
> who have had their
> 
> players and guilds finding each other
> players and guilds find each other
