### ISSUE TITLE
Can create ads for any guild, even if not guild leader/officer

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#308]
Reported through reddit: 

> Is it intentional that you're able to make a guild ad even if you're not an officer/GM just by connecting your b.net? Was able to make pages for guilds I have lv1 alts in.

Can't check.

**Comment by bmagic** [comment]
C'est intentionnel. Si un GM de la guilde passe par là il pourra verrouiller qui a le droit d'éditer la guilde mais tant qu'il n'est pas passé, alors tout le monde dans la guilde peut l'éditer.
