### ISSUE TITLE
weird bug on velhari kill date 

### ISSUE THREAD

**Issue by itcotta** [warcraftlfg/warcraft-lfg#313]
At the time of writting this when accessing : https://www.warcraftlfg.com/#/guild/eu/Sunstrider/Aphorism/
it shows that velhari was killed 16 years ago http://puu.sh/pjmDk/2efdc52eaf.png

**Comment by bmagic** [comment]
Thx to your report !!! I have just fixed it.

We currently create our own ranking api because Wowprogress ban us ... Their are some bug to fix and we will be ok ;)
