### ISSUE TITLE
Polish - About us review

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#39]
Fix de quelques typos et phases pas claires: 
## About WarcraftLFG

We strive to be the link between players and guilds: Our goal is to provide each party with a meaningful set of data to help you find your perfect guild mates.

Our data comes from various source, and we are truly thankful for the quality of data provided by both [WarcraftLogs](https://www.warcraftlogs.com/) and [WoWProgress](http://www.wowprogress.com)

For years, we felt that raiders and guilds alike were lacking a better way to find each other.
**WarcraftLFG** is our answer.
## Guilds

Tired of spamming the general chat with your recruitment macro? So were we. 

**WarcraftLFG** is a simple and intuitive tool to find your next guild mate in just a few clicks. Our database contains hundreds -and growing! - of potential candidates and our goal is to help you connect with them.
## Raiders

Your experience is invaluable. Hundreds of guilds are desperate to find you. **WarcraftLFG** helps you connect with them in a simple yet efficient way.
### About us

We are a team of passionate raiders and developers playing WoW for the last decade.
We are committed to support **WarcraftLFG** for as long as you’re going to use it: We are already working hard on implementing rich and powerful features which should keep us busy for the next decade already.

**Comment by bmagic** [comment]
Je suis dessus
