### ISSUE TITLE
Bug: Language Filters

### ISSUE THREAD

**Issue by daleadae** [warcraftlfg/warcraft-lfg#40]
![pasted image at 2015_11_28 11_03 am](https://cloud.githubusercontent.com/assets/7361756/11451488/16a224c2-95c0-11e5-8c50-97cc18f09b02.png)
![pasted image at 2015_11_28 11_04 am](https://cloud.githubusercontent.com/assets/7361756/11451489/17eba790-95c0-11e5-960e-9309ecc7b655.png)

Selecting any language (from 1 to all) will hide any character with n/a set as his language.

Possible que seul Alogon puisse se tag n/a ceci dit!

**Comment by bmagic** [comment]
Pas un bug pour moi !!! J'avantage les gars qui renseignent. Si ils renseignent pas ils sont pas vu.
