### ISSUE TITLE
Créer le design de la page Character List

### ISSUE THREAD

**Issue by bmagic** [warcraftlfg/warcraft-lfg#6]
Il faut créer un design avec les filtres et paramètres suivants : 

Filtres: 
- Région 
- Faction 
- Language 
- Roles 
- Classes
- Raids per week 
- Raid days 
- Level 100 

Information à afficher par character : 
- Faction 
- Name 
- Realm 
- Region 
- Role (can be empty)
- Guild (can be empty)
- Level 
- ilvl 
- Ring (can be empty) 
- Languages (can be empty) 
- Raids per week  
- Raids days avec horaires (can be empty) 
- Progress (can be empty) 
- Warcraftlogs (can be empty) 
- Update Date

**Comment by Zzbrah** [comment]
fait.
